
notifications:
  email:
    on_success: change
    on_failure: always

language: swift

stages:
  - Tests
  - Compatibility

jobs:
  include:
    - stage: Tests
      os: linux
      dist: trusty
      name: Linux Swift 5.0
      env:
        - SWIFT_BRANCH=swift-5.0-release
        - SWIFT_VERSION=swift-5.0-RELEASE
      install:
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar -xz -C swift
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
      script: swift test
    - stage: Tests
      os: osx
      osx_image: xcode10.2
      name: macOS Tests
      script: swift test
