name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@master
    - name: Build
      run: |
        swift --version
        swift package reset
        swift build
    - name: Test
      run: swift test -c release
